### PR TITLE
Feature/mach fixes

### PR DESCRIPTION
**Pull request by timblechmann**

### CODE REVIEW

**Comment by Lastique** [comment]
Why the change to `manual_reset_event`?

It makes it non-mach specific. If we do it, it should be renamed to manual_reset_event_semaphore.hpp.

**Comment by timblechmann** [comment]
> Why the change to `manual_reset_event`?
> 
> It makes it non-mach specific. If we do it, it should be renamed to manual_reset_event_semaphore.hpp.

technically it's still the implementation as for mach systems. but some mach systems have semaphores other than mach semaphores, which are the preferred semaphore implementation: macos with it's dispatch semaphores ...

don't really have a strong opinion on the naming here, but have a small tendency to keep it as it is to reflect this

**Comment by Lastique** [comment]
We do have `auto_reset_event_semaphore.hpp`, which is used in the same conditions as `manual_reset_event_mach.hpp`, so I would prefer some consistency. Generally, the naming reflects the platform if the implementation will not work on any other platform (i.e. it is mach if it won't compile on e.g. Linux, which also has semaphores). Which implementation we prefer on a given platform is a separate matter, not related to the naming.

**Comment by timblechmann** [comment]
> We do have `auto_reset_event_semaphore.hpp`, which is used in the same conditions as `manual_reset_event_mach.hpp`, so I would prefer some consistency.

the selection logic is a little different, though ... iirc we've done this for a reason

> Generally, the naming reflects the platform if the implementation will not work on any other platform (i.e. it is mach if it won't compile on e.g. Linux, which also has semaphores). Which implementation we prefer on a given platform is a separate matter, not related to the naming.

well, on linux we don't want to use the implementation via semaphores, because we have a futex-based implementation. on win32 also has semaphores, but events as first-class synchronisation mechanism ... those are the preferred implementations which are preferred on those platforms ...

**Comment by Lastique** [comment]
> those are the preferred implementations which are preferred on those platforms

Yes, and that is done by the selection logic via preprocessor. It doesn't make the new `manual_reset_event` incompatible with other platforms, and potentially one could use it there, for whatever reason. We could support a new platform where the semaphore-based implementation would be optimal. So my point is that so long as the code is not tied specifically to Mac OS X, it should not be named mach.

**Comment by timblechmann** [comment]
well, the change to `manual_reset_event` was broken, anyway, as the implementation relies on mach's `semaphore_signal_all`, which is really mach-specific and cannot be implemented with other semaphore APIs. dropped that part of the PR

**Comment by Lastique** [comment]
Ok, thanks.

**Pull request merged**
